M48
; DRILL file {KiCad 9.0.7} date 2026-02-11T09:08:56+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-11T09:08:56+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X96.635Y-44.435
X101.485Y-44.435
T2
X96.335Y-41.405
X101.785Y-41.405
M30
